version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=XXXXX
      - USER_GID=XXXXX
    restart: always
    networks:
      - gitea
    volumes:
      - /volume1/docker/gitea/dataFolder/data:/data
      - /volume1/docker/gitea/gitea-dockercompose/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
